apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ceph-csi-nvmeof-nodeplugin-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-nvmeof-nodeplugin-r
subjects:
- kind: ServiceAccount
  name: ceph-csi-nvmeof-nodeplugin-sa
  namespace: ceph-csi-system
