apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ceph-csi-nvmeof-ctrlplugin-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-nvmeof-ctrlplugin-r
subjects:
- kind: ServiceAccount
  name: ceph-csi-nvmeof-ctrlplugin-sa
  namespace: ceph-csi-system
